name: PlatformIO CI

on: 
  pull_request:
  push:
    branches: 
      - main

jobs:
  vue-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - uses: devops-actions/action-get-tag@v1.0.1
        id: tag
        with:
          strip_v: true # Optional: Remove 'v' character from version
          default: v0.0.0 # Optional: Default version when tag not found
        
      - run: |
          REV=`git rev-parse HEAD | rev | cut -c 1-6 | rev`
          echo "VUE_APP_BUILD=..$REV" >> .env
          echo "VUE_APP_VERSION=${{steps.tag.outputs.tag}}" >> .env
          cat .env

      - run: npm install
      - run: npm run build 
                
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version. https://github.com/marketplace/actions/add-commit
        with:
          add: 'dist'
          author_name: GitHub Action
          author_email: mp-se@noreply.github.com
          default_author: github_actor
          message: 'GitHub Action Build'
          pathspec_error_handling: ignore
